// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjekatPrvaApp;

namespace ProjekatPrvaApp.Migrations
{
    [DbContext(typeof(HilbertContext))]
    partial class HilbertContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjekatPrvaApp.Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("ProjekatPrvaApp.Models.Soba", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("brojGostiju")
                        .HasColumnType("int");

                    b.Property<int>("brojKreveta")
                        .HasColumnType("int");

                    b.Property<double>("cijena")
                        .HasColumnType("float");

                    b.Property<int?>("korisnikID")
                        .HasColumnType("int");

                    b.Property<int>("stanjeSobe")
                        .HasColumnType("int");

                    b.Property<bool>("zauzetostSobe")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("korisnikID");

                    b.ToTable("Soba");
                });

            modelBuilder.Entity("ProjekatPrvaApp.Models.Soba", b =>
                {
                    b.HasOne("ProjekatPrvaApp.Models.Korisnik", "korisnik")
                        .WithMany()
                        .HasForeignKey("korisnikID");
                });
#pragma warning restore 612, 618
        }
    }
}
